public enum TokenType
{
    IDENT, INTCONST , MENOR, MENORIGUAL, MAIOR, MAIORIGUAL,
    IGUALDADE, DIFERENTEIGUAL, BARRA, ASTERISCO, COLCHEABERTO, COLCHEFECHADO,
    INTTIPO, VOIDTIPO, IGUAL, SIMBOLOMAIS, SIMBOLOMENOS,
    PARABERTO, PARFECHADO, PONTO, VIRGULA, PONTOVIRGULA, CHAVEABERTO, CHAVEFECHADO,
    IF, WHILE, RETURN, ELSE

}