public enum TokenType
{
    IDENT, INTCONST , MENOR, MENORIGUAL, MAIOR, MAIORIGUAL,
    IGUALDADE, DIFERENTEIGUAL, BARRA, ASTERISCO, COLCHEABERTO, COLCHEFECHADO,
    INTTIPO, VOIDTIPO,
    PARABERTO, PARFECHADO, PONTO

}